### ISSUE TITLE
two standards shall be RFC5880, and RFC5881

### ISSUE THREAD

**Issue by SamDing98** [beni-sandu/libnetbfd#1]
hi, typo here, shall be RFC5880, and 5881
![image](https://github.com/beni-sandu/libnetbfd/assets/143687493/bd3edef1-928e-49d4-a874-25255c559424)

**Comment by beni-sandu** [comment]
Hey @SamDing98 , I actually never noticed, although it has been there since the beginning. If you want to send a patch yourself, let me know, otherwise I will adjust it soon.

Thanks!

**Comment by beni-sandu** [comment]
Fixed now, thanks for the ping.
